package resources.views.component.navigation;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import system.library.Navigation;


public class NavItem extends javax.swing.JPanel {
    
    private boolean selected;
    private boolean over;
    
    public NavItem(Navigation data) {
        initComponents();
        setOpaque(false);
        if (data.getType() == Navigation.MenuType.MENU) {
            labelNavIcon.setIcon(data.toIcon());
            labelNavName.setText(data.getName());
        } else if (data.getType() == Navigation.MenuType.TITLE) {
            setPreferredSize(new Dimension(112, 50));
            labelNavIcon.setText(data.getName());
            labelNavIcon.setFont(new Font("Segoe UI", 1, 14));
            labelNavIcon.setForeground(Color.decode("#EEEEEE"));
            labelNavName.setVisible(false);
        } else {
            labelNavName.setText(" ");
        }
    }
    
    public void setSelected(boolean selected) {
        this.selected = selected;
        repaint();
    }
    
    public void setOver(boolean over) {
        this.over = over;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNavIcon = new javax.swing.JLabel();
        labelNavName = new javax.swing.JLabel();

        labelNavName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNavName.setForeground(new java.awt.Color(238, 238, 238));
        labelNavName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNavIcon)
                .addGap(18, 18, 18)
                .addComponent(labelNavName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNavIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNavName, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    @Override
    protected void paintComponent(Graphics g) {
        if (selected || over) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            if (selected) {
                g2.setColor(new Color(255, 255, 255, 80));
            } else {
                g2.setColor(new Color(255, 255, 255, 40));
            }
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        }
        super.paintComponent(g);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelNavIcon;
    private javax.swing.JLabel labelNavName;
    // End of variables declaration//GEN-END:variables
}
