package resources.views.component;

public class PanelNotification extends javax.swing.JPanel {

    public void notify(String type, String message) {
        this.setVisible(true);
        switch (type) {
            case "error":
                errorNotify();
                break;
            case "success":
                successNotify();
                break;
            default:
                defaultNotify();
        }
        labelMessage.setText(message);
    }
    
    private void errorNotify() {
        labelMessage.setForeground(new java.awt.Color(255, 131, 141));
        setBackground(new java.awt.Color(255, 204, 204));
        setBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 153)), 
                javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 153, 153))
            )
        );
        btnCloseNotif.setBackground(new java.awt.Color(255, 204, 204));
        btnCloseNotif.setBorderColor(new java.awt.Color(255, 204, 204));
        btnCloseNotif.setColor(new java.awt.Color(255, 204, 204));
        btnCloseNotif.setColorClick(new java.awt.Color(255, 204, 204));
        btnCloseNotif.setColorOver(new java.awt.Color(255, 204, 204));
    }
    
    private void successNotify() {
        labelMessage.setForeground(new java.awt.Color(76, 175, 80));
        setBackground(new java.awt.Color(212, 237, 218));
        setBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(76, 175, 80)), 
                javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(76, 175, 80))
            )
        );
        btnCloseNotif.setBackground(new java.awt.Color(212, 237, 218));
        btnCloseNotif.setBorderColor(new java.awt.Color(212, 237, 218));
        btnCloseNotif.setColor(new java.awt.Color(212, 237, 218));
        btnCloseNotif.setColorClick(new java.awt.Color(212, 237, 218));
        btnCloseNotif.setColorOver(new java.awt.Color(212, 237, 218));
    }
    
    private void defaultNotify() {
        labelMessage.setForeground(new java.awt.Color(204, 204, 204));
        setBackground(new java.awt.Color(238, 238, 238));
        setBorder(
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 221, 221)),
                javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(221, 221, 221))
            )
        );
        btnCloseNotif.setBackground(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setBorderColor(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColor(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColorClick(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColorOver(new java.awt.Color(238, 238, 238));
    }
    
    public PanelNotification() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCloseNotif = new resources.views.component.button.FlatButton();
        labelMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(221, 221, 221)), javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(221, 221, 221))));

        btnCloseNotif.setBackground(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/close.png"))); // NOI18N
        btnCloseNotif.setBorderColor(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColor(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColorClick(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setColorOver(new java.awt.Color(238, 238, 238));
        btnCloseNotif.setMaximumSize(new java.awt.Dimension(46, 46));
        btnCloseNotif.setMinimumSize(new java.awt.Dimension(46, 46));
        btnCloseNotif.setPreferredSize(new java.awt.Dimension(46, 46));
        btnCloseNotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseNotifAct(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(204, 204, 204));
        labelMessage.setText("Notification");
        labelMessage.setToolTipText("");
        labelMessage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 7));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnCloseNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCloseNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseNotifAct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseNotifAct
        labelMessage.setText(" ");
        defaultNotify();
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseNotifAct


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.views.component.button.FlatButton btnCloseNotif;
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables
}
