package resources.views.component;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import resources.event.EventMenuSelected;
import system.library.Helper;
import system.library.Navigation;
import system.library.json.Menu;

public class PanelNavbar extends javax.swing.JPanel {

    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        navList.addEventMenuSelected(event);
    }
    
    public String getPageName() {
        return navList.getPageName();
    }

    public void setPageName(String pageName) {
        navList.setPageName(pageName);
    }
    
    public PanelNavbar() {
        initComponents();
        setOpaque(false);
        scrollPaneNav.getViewport().setOpaque(false);
        scrollPaneNav.setVerticalScrollBar(new ScrollBarFlat());
        scrollPaneNav.setBackground(new Color(242, 242, 242, 80));
        navList.setOpaque(false);
    }
    
    public void menuList(String position) {
        
        try {
            system.library.json.structure.Menu menu = Menu.data();
            
            if (menu.getData() != null) {
                int i = 0;
                for (system.library.json.structure.MenuList list : menu.getData()) {
                    if (
                        list.getPermission().length == 0 ||
                        Helper.inArray(position, list.getPermission())
                    ) {
                        if (list.getType().equals("menu")) {
                            navList.addItem(new Navigation(
                                list.getIcon(), 
                                list.getName(), 
                                list.getMenu(), 
                                Navigation.MenuType.MENU
                            ));
                        } else {
                            navList.addItem(new Navigation(
                                list.getIcon(), 
                                list.getName(), 
                                list.getMenu(), 
                                Navigation.MenuType.TITLE
                            ));
                        }
                    }
                }
            }
        } catch (Exception e) {
            System.err.println("PanelNavbar Menu.data Err: " + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneNav = new javax.swing.JScrollPane();
        navList = new resources.views.component.navigation.NavList<>();

        setMaximumSize(new java.awt.Dimension(250, 670));
        setMinimumSize(new java.awt.Dimension(250, 670));
        setPreferredSize(new java.awt.Dimension(250, 670));

        scrollPaneNav.setBorder(null);
        scrollPaneNav.setViewportBorder(javax.swing.BorderFactory.createCompoundBorder());

        scrollPaneNav.setViewportView(navList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneNav, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(scrollPaneNav, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(
                RenderingHints.KEY_ANTIALIASING, 
                RenderingHints.VALUE_ANTIALIAS_ON
        );
        GradientPaint grd = new GradientPaint(
                0, 
                0, 
                Color.decode("#abd04e"), 
                0, 
                getHeight(), 
                Color.decode("#48703a")
        );
        g2.setPaint(grd);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 0, 0);
        super.paintChildren(g);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.views.component.navigation.NavList<String> navList;
    private javax.swing.JScrollPane scrollPaneNav;
    // End of variables declaration//GEN-END:variables

}
