package resources.views.page.investor;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import resources.views.component.ScrollBarFlat;
import resources.views.page.investor.table.stock.ModelTable;

public class AddStockForm extends javax.swing.JPanel {
    
    private resources.views.layout.Main frame;
    
    private int investorId;
    
    // pages
    private MainForm main;
    
    public AddStockForm(resources.views.layout.Main frm) {
        try {
            this.frame = frm;
            
            init();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    public AddStockForm() {
        try {
            init();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    public void init() {
        initComponents();
        
        try {
            initComponents();
            
            panelNotification.setVisible(false);
        
            Object sessId = (Object) this.frame.session.getItem("id");

            if(sessId != null) {
               this.investorId = (int) sessId;
            } else {
               this.investorId = 0;
            }
            
            loadTotalStock(this.investorId);
            
            setData(this.investorId);
            
            resetData();
            
            scrollTable.setVerticalScrollBar(new ScrollBarFlat());
            scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
            scrollTable.getViewport().setBackground(Color.WHITE);

            JPanel p = new JPanel();
            p.setBackground(Color.WHITE);
            scrollTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
            
            loadTable(this.investorId, null);
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    private void setData(int investorId) {
        System.out.println("Investor ID: " + investorId);
        
        scrollNote.setVerticalScrollBar(new ScrollBarFlat());
        inputNote.setLineWrap(true);

        inputInvestorId.setVisible(false);
        inputInvestorId.setText(String.valueOf(investorId));
        
        inputBuyPrice.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ( ((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
                    e.consume();  // if it's not a number, ignore the event
                }
             }
        });
    }
    
    private void resetData() {
        inputNoSaham.setText("");
        inputBuyPrice.setText("");
        inputBuyDate.setDate(null);
        inputNoBukti.setText("");
        inputNote.setText("");
    }

    private void loadTotalStock(int investorId) {
        try {
            app.controllers.SahamController stockCtrl = new app.controllers.SahamController();
            
            int totalStock = stockCtrl.totalStock(investorId);
            
            labelTotalStockValue.setText(String.format("%,d", totalStock));
        } catch (Exception e) {
            System.err.println(e.getMessage());
            labelTotalStockValue.setText("0");
        }
    }
    
    private void loadTable(int investorId, String param) {
        
        param = param != null ? param : "";
        
        table.clearRows();
        
        try {
            app.controllers.SahamController stockCtrl = new app.controllers.SahamController();
            
            List<Map<String, Object>> list = stockCtrl.listTable(investorId, param);
            
            if(list != null) {
                int no = 1;
            
                for (Map<String, Object> map : list) {

                    table.addRow(
                        new ModelTable(
                            (int) map.get("id"),
                            no,
                            (String) map.get("name"),
                            (String) map.get("no_saham"),
                            (String) map.get("no_bukti"),
                            (String) map.get("buy_date"),
                            String.format("%,d", map.get("buy_price"))
                        ).toRowTable()
                    );

                    no++;
                }
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNotification = new resources.views.component.PanelNotification();
        panelButton = new javax.swing.JPanel();
        btnBack = new resources.views.component.button.FlatButton();
        PanelCardAdd = new javax.swing.JPanel();
        panelCardAddHeader = new javax.swing.JPanel();
        labelAddTitle = new javax.swing.JLabel();
        inputInvestorId = new javax.swing.JTextField();
        labelNoSaham = new javax.swing.JLabel();
        inputNoSaham = new javax.swing.JTextField();
        labelBuyDate = new javax.swing.JLabel();
        inputBuyDate = new com.toedter.calendar.JDateChooser();
        labelBuyPrice = new javax.swing.JLabel();
        inputBuyPrice = new javax.swing.JTextField();
        labelNoBukti = new javax.swing.JLabel();
        inputNoBukti = new javax.swing.JTextField();
        labelNote = new javax.swing.JLabel();
        scrollNote = new javax.swing.JScrollPane();
        inputNote = new javax.swing.JTextArea();
        panelCardAddFooter = new javax.swing.JPanel();
        btnSave = new resources.views.component.button.FlatButton();
        panelCardTable = new javax.swing.JPanel();
        panelCardTableHeader = new javax.swing.JPanel();
        labelTotakStock = new javax.swing.JLabel();
        labelTotalStockValue = new javax.swing.JLabel();
        labelTableTitle = new javax.swing.JLabel();
        panelCardTableSearch = new javax.swing.JPanel();
        btnSearch = new resources.views.component.button.FlatButton();
        inputSearch = new javax.swing.JTextField();
        scrollTable = new javax.swing.JScrollPane();
        table = new resources.views.page.investor.table.stock.TablePage();

        setBackground(new java.awt.Color(238, 238, 238));
        setForeground(new java.awt.Color(238, 238, 238));

        panelButton.setBackground(new java.awt.Color(238, 238, 238));
        panelButton.setForeground(new java.awt.Color(238, 238, 238));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/left-arrow.png"))); // NOI18N
        btnBack.setBorderColor(new java.awt.Color(255, 255, 255));
        btnBack.setColor(new java.awt.Color(255, 255, 255));
        btnBack.setColorClick(new java.awt.Color(255, 255, 255));
        btnBack.setColorOver(new java.awt.Color(255, 255, 255));
        btnBack.setRadius(10);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAct(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        PanelCardAdd.setBackground(new java.awt.Color(255, 255, 255));
        PanelCardAdd.setForeground(new java.awt.Color(255, 255, 255));

        panelCardAddHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(238, 238, 238)));
        panelCardAddHeader.setOpaque(false);

        labelAddTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAddTitle.setForeground(new java.awt.Color(51, 51, 51));
        labelAddTitle.setText("Tambah Saham");

        javax.swing.GroupLayout panelCardAddHeaderLayout = new javax.swing.GroupLayout(panelCardAddHeader);
        panelCardAddHeader.setLayout(panelCardAddHeaderLayout);
        panelCardAddHeaderLayout.setHorizontalGroup(
            panelCardAddHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardAddHeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelAddTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCardAddHeaderLayout.setVerticalGroup(
            panelCardAddHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardAddHeaderLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(labelAddTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        inputInvestorId.setBackground(new java.awt.Color(255, 255, 255));
        inputInvestorId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputInvestorId.setForeground(new java.awt.Color(51, 51, 51));
        inputInvestorId.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 17, 17)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        inputInvestorId.setEnabled(false);

        labelNoSaham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNoSaham.setForeground(new java.awt.Color(0, 0, 0));
        labelNoSaham.setText("No Saham");

        inputNoSaham.setBackground(new java.awt.Color(255, 255, 255));
        inputNoSaham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNoSaham.setForeground(new java.awt.Color(51, 51, 51));
        inputNoSaham.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));

        labelBuyDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelBuyDate.setForeground(new java.awt.Color(0, 0, 0));
        labelBuyDate.setText("Tanggal Beli");

        inputBuyDate.setBackground(new java.awt.Color(255, 255, 255));
        inputBuyDate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 17, 17)), null));
        inputBuyDate.setForeground(new java.awt.Color(255, 255, 255));
        inputBuyDate.setDateFormatString("yyyy-MM-dd");
        inputBuyDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputBuyDate.setNextFocusableComponent(inputNoBukti);

        labelBuyPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelBuyPrice.setForeground(new java.awt.Color(0, 0, 0));
        labelBuyPrice.setText("Total Beli (Rp)");

        inputBuyPrice.setBackground(new java.awt.Color(255, 255, 255));
        inputBuyPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputBuyPrice.setForeground(new java.awt.Color(51, 51, 51));
        inputBuyPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputBuyPrice.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));

        labelNoBukti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNoBukti.setForeground(new java.awt.Color(0, 0, 0));
        labelNoBukti.setText("No Bukti");

        inputNoBukti.setBackground(new java.awt.Color(255, 255, 255));
        inputNoBukti.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNoBukti.setForeground(new java.awt.Color(51, 51, 51));
        inputNoBukti.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));

        labelNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNote.setForeground(new java.awt.Color(0, 0, 0));
        labelNote.setText("Catatan");

        scrollNote.setBorder(null);
        scrollNote.setHorizontalScrollBar(null);

        inputNote.setBackground(new java.awt.Color(255, 255, 255));
        inputNote.setColumns(20);
        inputNote.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inputNote.setForeground(new java.awt.Color(51, 51, 51));
        inputNote.setRows(5);
        inputNote.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(17, 17, 17)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        scrollNote.setViewportView(inputNote);

        panelCardAddFooter.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(238, 238, 238)));
        panelCardAddFooter.setOpaque(false);

        btnSave.setText("Tambah");
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setRadius(10);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAct(evt);
            }
        });

        javax.swing.GroupLayout panelCardAddFooterLayout = new javax.swing.GroupLayout(panelCardAddFooter);
        panelCardAddFooter.setLayout(panelCardAddFooterLayout);
        panelCardAddFooterLayout.setHorizontalGroup(
            panelCardAddFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCardAddFooterLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCardAddFooterLayout.setVerticalGroup(
            panelCardAddFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCardAddFooterLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelCardAddLayout = new javax.swing.GroupLayout(PanelCardAdd);
        PanelCardAdd.setLayout(PanelCardAddLayout);
        PanelCardAddLayout.setHorizontalGroup(
            PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCardAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCardAddFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCardAddHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCardAddLayout.createSequentialGroup()
                        .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCardAddLayout.createSequentialGroup()
                                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelCardAddLayout.createSequentialGroup()
                                        .addComponent(labelBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(PanelCardAddLayout.createSequentialGroup()
                                            .addComponent(labelNoSaham, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inputNoSaham))
                                        .addGroup(PanelCardAddLayout.createSequentialGroup()
                                            .addComponent(labelNoBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(inputNoBukti))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelBuyPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCardAddLayout.createSequentialGroup()
                                .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollNote)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputInvestorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        PanelCardAddLayout.setVerticalGroup(
            PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCardAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelCardAddHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNoSaham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputNoSaham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputInvestorId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBuyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputBuyPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNoBukti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNoBukti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCardAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(panelCardAddFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        panelCardTable.setBackground(new java.awt.Color(255, 255, 255));
        panelCardTable.setForeground(new java.awt.Color(255, 255, 255));

        panelCardTableHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(238, 238, 238)));
        panelCardTableHeader.setOpaque(false);

        labelTotakStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotakStock.setForeground(new java.awt.Color(51, 51, 51));
        labelTotakStock.setText("Total Saham (Rp) :");

        labelTotalStockValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotalStockValue.setForeground(new java.awt.Color(51, 51, 51));
        labelTotalStockValue.setText("0");

        labelTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTableTitle.setForeground(new java.awt.Color(51, 51, 51));
        labelTableTitle.setText("Daftar Saham");

        javax.swing.GroupLayout panelCardTableHeaderLayout = new javax.swing.GroupLayout(panelCardTableHeader);
        panelCardTableHeader.setLayout(panelCardTableHeaderLayout);
        panelCardTableHeaderLayout.setHorizontalGroup(
            panelCardTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardTableHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTotakStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotalStockValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTableTitle)
                .addContainerGap())
        );
        panelCardTableHeaderLayout.setVerticalGroup(
            panelCardTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardTableHeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelCardTableHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTotakStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTotalStockValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        panelCardTableSearch.setOpaque(false);

        btnSearch.setBackground(new java.awt.Color(0, 123, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/search.png"))); // NOI18N
        btnSearch.setBorderColor(new java.awt.Color(0, 123, 255));
        btnSearch.setColor(new java.awt.Color(0, 123, 255));
        btnSearch.setColorClick(new java.awt.Color(2, 112, 229));
        btnSearch.setColorOver(new java.awt.Color(2, 112, 229));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAct(evt);
            }
        });

        inputSearch.setBackground(new java.awt.Color(255, 255, 255));
        inputSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputSearch.setForeground(new java.awt.Color(102, 102, 102));
        inputSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        inputSearch.setOpaque(true);

        javax.swing.GroupLayout panelCardTableSearchLayout = new javax.swing.GroupLayout(panelCardTableSearch);
        panelCardTableSearch.setLayout(panelCardTableSearchLayout);
        panelCardTableSearchLayout.setHorizontalGroup(
            panelCardTableSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardTableSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCardTableSearchLayout.setVerticalGroup(
            panelCardTableSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(inputSearch)
        );

        scrollTable.setBorder(null);
        scrollTable.setViewportView(table);

        javax.swing.GroupLayout panelCardTableLayout = new javax.swing.GroupLayout(panelCardTable);
        panelCardTable.setLayout(panelCardTableLayout);
        panelCardTableLayout.setHorizontalGroup(
            panelCardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCardTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollTable)
                    .addComponent(panelCardTableHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCardTableSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelCardTableLayout.setVerticalGroup(
            panelCardTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelCardTableHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelCardTableSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCardTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCardAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNotification, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(PanelCardAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelCardTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveAct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAct
        
        int investorId = Integer.valueOf(inputInvestorId.getText());
        String noSaham = inputNoSaham.getText();
        int buyPrice = Integer.valueOf(inputBuyPrice.getText());
        String buyDate;
        if(inputBuyDate.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat(inputBuyDate.getDateFormatString());
            buyDate = sdf.format(inputBuyDate.getDate());
        } else {
            buyDate = "";
        }
        String noBukti = inputNoBukti.getText();
        String notes = inputNote.getText();
        
        Map<String, Object> map = new HashMap<String, Object>();
        
        map.put("no_saham", noSaham);
        map.put("investor_id", investorId);
        map.put("buy_price", buyPrice);
        map.put("buy_date", buyDate);
        map.put("no_bukti", noBukti);
        map.put("notes", notes);
        
        System.out.println("investorId: " + investorId);
        System.out.println("noSaham: " + noSaham);
        System.out.println("buyPrice: " + buyPrice);
        System.out.println("buyDate: " + buyDate);
        System.out.println("noBukti: " + noBukti);
        System.out.println("notes: " + notes);
        System.out.println("--------------------------------------");
        
        app.controllers.SahamController stockCtrl = new app.controllers.SahamController();
        
        boolean res = stockCtrl.process(map);

        if(res == true) {
            panelNotification.notify("success", "Saham Berhasil Ditambah.");
            
            resetData();
            
            loadTotalStock(this.investorId);
            
            loadTable(this.investorId, null);
        } else {
            panelNotification.notify("error", "Saham Gagal Ditambah.");
        }
    }//GEN-LAST:event_btnSaveAct

    private void btnBackAct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAct
        main = new MainForm(this.frame);

        this.frame.setPage(main);
    }//GEN-LAST:event_btnBackAct

    private void btnSearchAct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAct
        String param = inputSearch.getText().toLowerCase();

        loadTable(this.investorId, param);
    }//GEN-LAST:event_btnSearchAct


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCardAdd;
    private resources.views.component.button.FlatButton btnBack;
    private resources.views.component.button.FlatButton btnSave;
    private resources.views.component.button.FlatButton btnSearch;
    private com.toedter.calendar.JDateChooser inputBuyDate;
    private javax.swing.JTextField inputBuyPrice;
    private javax.swing.JTextField inputInvestorId;
    private javax.swing.JTextField inputNoBukti;
    private javax.swing.JTextField inputNoSaham;
    private javax.swing.JTextArea inputNote;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel labelAddTitle;
    private javax.swing.JLabel labelBuyDate;
    private javax.swing.JLabel labelBuyPrice;
    private javax.swing.JLabel labelNoBukti;
    private javax.swing.JLabel labelNoSaham;
    private javax.swing.JLabel labelNote;
    private javax.swing.JLabel labelTableTitle;
    private javax.swing.JLabel labelTotakStock;
    private javax.swing.JLabel labelTotalStockValue;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelCardAddFooter;
    private javax.swing.JPanel panelCardAddHeader;
    private javax.swing.JPanel panelCardTable;
    private javax.swing.JPanel panelCardTableHeader;
    private javax.swing.JPanel panelCardTableSearch;
    private resources.views.component.PanelNotification panelNotification;
    private javax.swing.JScrollPane scrollNote;
    private javax.swing.JScrollPane scrollTable;
    private resources.views.page.investor.table.stock.TablePage table;
    // End of variables declaration//GEN-END:variables
}
