package resources.views.page.laporan.lunas;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import resources.views.component.ScrollBarFlat;
import resources.views.page.laporan.lunas.table.ModelTable;

/**
 *
 * @author Dwiki
 */
public class MainForm extends javax.swing.JPanel {
    
    private resources.views.layout.Main frame;   
   
    public MainForm(resources.views.layout.Main frm) {
        
        this.frame = frm;
        
        init();
    }
    
    public MainForm() {
        init();
    }
    
    private void init() {
        initComponents();
        
        String errMsg = (String) this.frame.session.getItem("errorNotif");
        
        String okMsg = (String) this.frame.session.getItem("successNotif");
        
        if(errMsg != null) {
            panelNotification.notify("error", errMsg);
        } else if(okMsg != null) {
            panelNotification.notify("success", okMsg);
        } else {
            panelNotification.setVisible(false);
        }
        
        scrollTable.setVerticalScrollBar(new ScrollBarFlat());
        scrollTable.getVerticalScrollBar().setBackground(Color.WHITE);
        scrollTable.getViewport().setBackground(Color.WHITE);
        
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        scrollTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        
        loadTable(null);
    }
    
     private void loadTable(String param) {
        param = param != null ? param : "";
        
        table.clearRows();
        
        try {
            app.controllers.LaporanController rprtCtrl = new app.controllers.LaporanController();
            
            List<Map<String, Object>> list = rprtCtrl.listTablePaidOff(param);
            
            for (Map<String, Object> map : list) {
                table.addRow(
                    new ModelTable(
                        (String) map.get("no_pengajuan"),
                        (String) map.get("nasabah"),
                        String.format("%,d", map.get("modal")),
                        String.format("%,d", map.get("est_laba")),
                        (String) map.get("lfn_date"),
                        (String) map.get("est_end")
                    ).toRowTable() 
                );
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNotification = new resources.views.component.PanelNotification();
        panelBtn = new javax.swing.JPanel();
        panelCard = new javax.swing.JPanel();
        panelCardHeader = new javax.swing.JPanel();
        labelTableTitle = new javax.swing.JLabel();
        btnSearch = new resources.views.component.button.FlatButton();
        inputSearch = new javax.swing.JTextField();
        scrollTable = new javax.swing.JScrollPane();
        table = new resources.views.page.laporan.lunas.table.TablePage();

        setBackground(new java.awt.Color(238, 238, 238));
        setForeground(new java.awt.Color(238, 238, 238));

        panelBtn.setBackground(new java.awt.Color(204, 204, 204));
        panelBtn.setForeground(new java.awt.Color(204, 204, 204));
        panelBtn.setOpaque(false);

        panelCard.setBackground(new java.awt.Color(255, 255, 255));
        panelCard.setForeground(new java.awt.Color(255, 255, 255));

        panelCardHeader.setOpaque(false);

        labelTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTableTitle.setForeground(new java.awt.Color(51, 51, 51));
        labelTableTitle.setText("Daftar Laporan");

        btnSearch.setBackground(new java.awt.Color(0, 123, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/search.png"))); // NOI18N
        btnSearch.setBorderColor(new java.awt.Color(0, 123, 255));
        btnSearch.setColor(new java.awt.Color(0, 123, 255));
        btnSearch.setColorClick(new java.awt.Color(2, 112, 229));
        btnSearch.setColorOver(new java.awt.Color(2, 112, 229));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAct(evt);
            }
        });

        inputSearch.setBackground(new java.awt.Color(255, 255, 255));
        inputSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        inputSearch.setForeground(new java.awt.Color(102, 102, 102));
        inputSearch.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        inputSearch.setOpaque(true);

        javax.swing.GroupLayout panelCardHeaderLayout = new javax.swing.GroupLayout(panelCardHeader);
        panelCardHeader.setLayout(panelCardHeaderLayout);
        panelCardHeaderLayout.setHorizontalGroup(
            panelCardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardHeaderLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(labelTableTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCardHeaderLayout.setVerticalGroup(
            panelCardHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardHeaderLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(labelTableTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inputSearch)
        );

        scrollTable.setBorder(null);
        scrollTable.setViewportView(table);

        javax.swing.GroupLayout panelCardLayout = new javax.swing.GroupLayout(panelCard);
        panelCard.setLayout(panelCardLayout);
        panelCardLayout.setHorizontalGroup(
            panelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollTable)
                    .addComponent(panelCardHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelCardLayout.setVerticalGroup(
            panelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelCardHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBtnLayout = new javax.swing.GroupLayout(panelBtn);
        panelBtn.setLayout(panelBtnLayout);
        panelBtnLayout.setHorizontalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBtnLayout.setVerticalGroup(
            panelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNotification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panelNotification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchAct(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAct
        String param = inputSearch.getText().toLowerCase();
        
        loadTable(param);
    }//GEN-LAST:event_btnSearchAct


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.views.component.button.FlatButton btnSearch;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JLabel labelTableTitle;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelCardHeader;
    private resources.views.component.PanelNotification panelNotification;
    private javax.swing.JScrollPane scrollTable;
    private resources.views.page.laporan.lunas.table.TablePage table;
    // End of variables declaration//GEN-END:variables
}
