/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resources.views.layout;

// Controllers
import app.controllers.AuthController;

import java.awt.Color;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dwiki
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        panelMoving.iniMoving(Login.this);
        labelNotif.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panelBorder = new resources.views.component.PanelBorder();
        panelBorderContent = new resources.views.component.PanelBorder();
        panelMoving = new resources.views.component.PanelMoving();
        btnClose = new resources.views.component.button.FlatButton();
        btnMinimize = new resources.views.component.button.FlatButton();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        inputUsername = new resources.views.component.form.InputText();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new resources.views.component.form.InputPassword();
        btnMasuk = new resources.views.component.button.FlatButton();
        labelNotif = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 600));
        setUndecorated(true);

        panelBorder.setBackground(new java.awt.Color(238, 238, 238));
        panelBorder.setForeground(new java.awt.Color(238, 238, 238));
        panelBorder.setMaximumSize(new java.awt.Dimension(380, 600));
        panelBorder.setMinimumSize(new java.awt.Dimension(380, 600));
        panelBorder.setPreferredSize(new java.awt.Dimension(380, 600));

        panelBorderContent.setBackground(new java.awt.Color(238, 238, 238));
        panelBorderContent.setForeground(new java.awt.Color(238, 238, 238));
        panelBorderContent.setMaximumSize(new java.awt.Dimension(380, 600));
        panelBorderContent.setMinimumSize(new java.awt.Dimension(380, 600));
        panelBorderContent.setPreferredSize(new java.awt.Dimension(380, 600));

        btnClose.setBackground(new java.awt.Color(238, 238, 238));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/close.png"))); // NOI18N
        btnClose.setBorderColor(new java.awt.Color(238, 238, 238));
        btnClose.setColor(new java.awt.Color(238, 238, 238));
        btnClose.setColorClick(new java.awt.Color(255, 51, 51));
        btnClose.setColorOver(new java.awt.Color(255, 51, 51));
        btnClose.setMaximumSize(new java.awt.Dimension(70, 70));
        btnClose.setMinimumSize(new java.awt.Dimension(70, 70));
        btnClose.setPreferredSize(new java.awt.Dimension(70, 70));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseApp(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(238, 238, 238));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/icons/minus.png"))); // NOI18N
        btnMinimize.setBorderColor(new java.awt.Color(238, 238, 238));
        btnMinimize.setColor(new java.awt.Color(238, 238, 238));
        btnMinimize.setColorClick(new java.awt.Color(221, 221, 221));
        btnMinimize.setColorOver(new java.awt.Color(221, 221, 221));
        btnMinimize.setMaximumSize(new java.awt.Dimension(70, 70));
        btnMinimize.setMinimumSize(new java.awt.Dimension(70, 70));
        btnMinimize.setPreferredSize(new java.awt.Dimension(70, 70));
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniApp(evt);
            }
        });

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMovingLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGroup(panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/assets/images/logo.png"))); // NOI18N

        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(72, 112, 58));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("KOPERASI SYARIAH");

        labelUsername.setBackground(new java.awt.Color(255, 255, 255));
        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(136, 136, 136));
        labelUsername.setText("Nama Pengguna/Nama Akun");
        labelUsername.setPreferredSize(new java.awt.Dimension(23, 16));

        inputUsername.setFontColor(new java.awt.Color(102, 102, 102));
        inputUsername.setPlaceholder("Masukan Nama Pengguna/Nama Akun");

        labelPassword.setBackground(new java.awt.Color(255, 255, 255));
        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(136, 136, 136));
        labelPassword.setText("Kata Sandi");
        labelPassword.setPreferredSize(new java.awt.Dimension(23, 16));

        inputPassword.setFontColor(new java.awt.Color(102, 102, 102));
        inputPassword.setPlaceholder("Masukan Kata Sandi Anda");

        btnMasuk.setText("MASUK");
        btnMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMasuk.setRadius(10);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionClickbtnMasuk(evt);
            }
        });

        labelNotif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNotif.setForeground(new java.awt.Color(255, 51, 51));
        labelNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNotif.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)), javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 51, 51))));

        javax.swing.GroupLayout panelBorderContentLayout = new javax.swing.GroupLayout(panelBorderContent);
        panelBorderContent.setLayout(panelBorderContentLayout);
        panelBorderContentLayout.setHorizontalGroup(
            panelBorderContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorderContentLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelBorderContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(inputUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(btnMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(labelNotif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelBorderContentLayout.setVerticalGroup(
            panelBorderContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderContentLayout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(logo)
                .addGap(12, 12, 12)
                .addComponent(title)
                .addGap(29, 29, 29)
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorderLayout = new javax.swing.GroupLayout(panelBorder);
        panelBorder.setLayout(panelBorderLayout);
        panelBorderLayout.setHorizontalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBorderLayout.setVerticalGroup(
            panelBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void actionClickbtnMasuk(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionClickbtnMasuk
        
        labelNotif.setVisible(false);
        labelNotif.setText("");
        
        // disable tombol
        btnMasuk.setText("MEMPROSES..");
        btnMasuk.setEnabled(false);
        
        // ambil data inputan
        String username = inputUsername.isInputNotNull() ? inputUsername.getText() : "";
        String password = inputPassword.isInputNotNull() 
                        ? inputPassword.getText()
                        : "";
        
        System.out.println("Username: " + username);
        
        System.out.println("Password: " + password);
        
        AuthController authCtrl = new AuthController();
        
        if(!username.isEmpty() && !password.isEmpty()) {
       
            try {
                boolean attempt = authCtrl.attempt(username, password);

                if(attempt) {
                    this.dispose();
                    //this.setVisible(false);
                    new Main().setVisible(true);
                } else {
                    btnMasuk.setText("MASUK");
                    btnMasuk.setEnabled(true);
                    
                    inputPassword.setText("");
                    inputPassword.requestFocusInWindow();
                    
                    labelNotif.setVisible(true);
                    labelNotif.setText("Nama Pengguna atau Kata Sandi Salah.");
                }
            } catch (ClassNotFoundException ex) {
                btnMasuk.setText("MASUK");
                btnMasuk.setEnabled(true);

                inputPassword.setText("");
                inputPassword.requestFocusInWindow();
                
                labelNotif.setVisible(true);
                labelNotif.setText("Error Class.");
            } catch (SQLException ex) {
                btnMasuk.setText("MASUK");
                btnMasuk.setEnabled(true);

                inputPassword.setText("");
                inputPassword.requestFocusInWindow();
                
                labelNotif.setVisible(true);
                labelNotif.setText("Error SQL.");
            }
        } else {
            btnMasuk.setText("MASUK");
            btnMasuk.setEnabled(true);
            
            if(username.isEmpty() && password.isEmpty()) {    
                inputUsername.requestFocusInWindow();
                
                labelNotif.setVisible(true);
                labelNotif.setText("Nama Pengguna atau Kata Sandi Tidak Boleh Kosong.");
            } else if(username.isEmpty()) {
                inputUsername.requestFocusInWindow();
                
                labelNotif.setVisible(true);
                labelNotif.setText("Nama Pengguna Tidak Boleh Kosong.");
            } else if (password.isEmpty()) {
                inputPassword.requestFocusInWindow();
                
                labelNotif.setVisible(true);
                labelNotif.setText("Kata Sandi Tidak Boleh Kosong.");
            }
        }
    }//GEN-LAST:event_actionClickbtnMasuk

    private void btnCloseApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseApp
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCloseApp

    private void btnMiniApp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniApp
        this.setExtendedState(javax.swing.JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMiniApp

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private resources.views.component.button.FlatButton btnClose;
    private resources.views.component.button.FlatButton btnMasuk;
    private resources.views.component.button.FlatButton btnMinimize;
    private resources.views.component.form.InputPassword inputPassword;
    private resources.views.component.form.InputText inputUsername;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNotif;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel logo;
    private resources.views.component.PanelBorder panelBorder;
    private resources.views.component.PanelBorder panelBorderContent;
    private resources.views.component.PanelMoving panelMoving;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
